objects:
  - pudding_box
  - tennis_ball
  - mug
  - apple
  - banana
  - bowl
corrected_init_pose:
  - [0.0, 0.0, 0.0, 0.0, 0.0, -0.45]
  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
config:
  r: 0.25
  alpha: 0.78
  n: 1
