only_first: True

experiment_1:
  objects:
    - 021_bleach_cleanser
    - 065-j_cups
    - 021_bleach_cleanser
    - 057_racquetball
    - 044_flat_screwdriver
    - 050_medium_clamp
    - 072-a_toy_airplane
  config:
    center: 0.4
    r: 0.05
    alpha: 1.57
    n: 1

experiment_2:
  objects:
    - 057_racquetball
    - 065-j_cups
    - 021_bleach_cleanser
    - 044_flat_screwdriver
    - 050_medium_clamp
    - 072-a_toy_airplane
  config:
    center: 0.4
    r: 0.25
    alpha: 0.78
    n: 1
