only_first: True

experiment_1:
  objects:
    - 057_racquetball
    - 065-j_cups
    - 021_bleach_cleanser
    - 044_flat_screwdriver
    - 050_medium_clamp
    - 072-a_toy_airplane
  corrected_init_pose:
    - [0.0, 0.0, 0.0, 0.0, 0.0, -0.45]
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  config:
    center: 0.4
    r: 0.15
    alpha: 1.57
    n: 1

experiment_2:
  objects:
    - 057_racquetball
    - 065-j_cups
    - 021_bleach_cleanser
    - 044_flat_screwdriver
    - 050_medium_clamp
    - 072-a_toy_airplane
  corrected_init_pose:
    - [0.0, 0.0, 0.0, 0.0, 0.0, -0.45]
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  config:
    center: 0.4
    r: 0.25
    alpha: 0.78
    n: 1

experiment_3:
  objects:
    - 057_racquetball
    - 065-j_cups
    - 021_bleach_cleanser
  corrected_init_pose:
    - [0.0, 0.0, 0.0, 0.0, 0.0, -0.45]
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  config:
    center: 0.4
    r: 0.25
    alpha: 0.78
    n: 1
